### ISSUE TITLE
Global coordinates of NaturalPoint

### ISSUE THREAD

**Issue by dimtsap** [isaar/MSolve#96]
TransformPointNaturalToGlobalCartesian method EvalShapeFunctions classes should take as input the shapeFunctions for a spefic NaturalPoint2D instead of the point itself. The current implementation only returns the cartesian transformation of a GaussPoint.

**Comment by SerafeimBakalakos** [comment]
Yes indeed that is all it does! The point of EvalShapeFunctions is to have all shapeFunctions evaluated at a specific NaturalPoint2D stored in an object, so that they can be distributed easily (and boy do they need to be distributed). The same holds for EvalShapeGradients2D (only shape function derivatives) and EvalInterpolation2D(shape functions and derivatives). Granted in the case of EvalShapeFunctions a simple array double[] would suffice, but I prefer being consistent. The NaturalPoint2D argument is not used and it must be removed.

**Comment by SerafeimBakalakos** [comment]
As it is now you have to call the much more verbose IIsoparametricInterpolation2D.EvaluateFunctionsAt(naturalPoint).TransformPointNaturalToGlobalCartesian (nodes) to calculate the shape functions at an arbitrary point. Therefore, I have added a similar TransformPointNaturalToGlobalCartesian(NaturalPoint2D naturalPoint, IReadOnlyList<Node2D> nodes)  to the interpolation class (IIsoparametricInterpolation2D),  which provides the functionality you requested for an arbitrary point. It will be included in the next pull request. EvalShapeFunctions.TransformPointNaturalToGlobalCartesian() and EvalInterpolation2D.TransformPointNaturalToGlobalCartesian() will remain as they are, since they avoid having to recompute the shape functions, but the useless NaturalPoint2D argument will be removed. Thanks for reporting it.
